
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import Navbar from "@/components/Navbar";
import { 
  ArrowRight, 
  CheckCircle, 
  Clock,
  LampDesk, 
  Palette, 
  ShoppingBag, 
  Sofa 
} from "lucide-react";
import { useEffect, useRef } from "react";

const Index = () => {
  const navigate = useNavigate();
  const heroRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleParallax = () => {
      if (!heroRef.current) return;
      const scrollY = window.scrollY;
      const heroElement = heroRef.current;
      heroElement.style.transform = `translateY(${scrollY * 0.25}px)`;
    };

    window.addEventListener("scroll", handleParallax);
    return () => window.removeEventListener("scroll", handleParallax);
  }, []);

  const features = [
    {
      icon: <Palette className="h-6 w-6" />,
      title: "AI-Powered Designs",
      description: "Get multiple interior design options generated by AI based on your preferences and room specifications."
    },
    {
      icon: <Sofa className="h-6 w-6" />,
      title: "Furniture Selection",
      description: "Browse and select from a curated collection of furniture pieces that match your style and budget."
    },
    {
      icon: <LampDesk className="h-6 w-6" />,
      title: "Customization",
      description: "Customize every aspect of your space including colors, materials, lighting, and accessories."
    },
    {
      icon: <ShoppingBag className="h-6 w-6" />,
      title: "Seamless Ordering",
      description: "Once you've finalized your design, easily order all the furniture through our supplier network."
    }
  ];

  const testimonials = [
    {
      quote: "The design suggestions were exactly what I was looking for. The process was so simple and the results were amazing.",
      author: "Sarah Johnson",
      role: "Homeowner"
    },
    {
      quote: "I was skeptical about AI-generated designs, but I'm incredibly impressed with what Interior Synergy produced for my living room.",
      author: "Michael Chen",
      role: "Apartment Owner"
    },
    {
      quote: "The BOQ feature saved me countless hours of research and comparison shopping. Everything arrived exactly as shown in the designs.",
      author: "Jessica Williams",
      role: "Home Renovator"
    }
  ];

  return (
    <div className="min-h-screen">
      <Navbar />
      
      {/* Hero Section */}
      <section className="relative h-screen overflow-hidden">
        <div 
          className="absolute inset-0 z-0"
          ref={heroRef}
        >
          <img 
            src="https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1932&q=80" 
            alt="Modern interior design" 
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-black/70 to-black/30" />
        </div>
        
        <div className="relative z-10 container mx-auto px-6 h-full flex items-center">
          <div className="max-w-2xl text-white pt-20">
            <span className="inline-block px-3 py-1 rounded-full bg-white/10 backdrop-blur-sm text-sm font-medium mb-6 animate-fade-in">
              Reimagine Your Space
            </span>
            <h1 className="font-serif text-4xl md:text-5xl lg:text-6xl font-semibold mb-6 leading-tight animate-fade-up [animation-delay:200ms]">
              Transform Your Home with AI-Powered Interior Design
            </h1>
            <p className="text-lg md:text-xl text-white/80 mb-8 max-w-lg animate-fade-up [animation-delay:400ms]">
              Generate stunning interior designs, customize to your taste, and purchase furniture effortlessly.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 animate-fade-up [animation-delay:600ms]">
              <Button 
                className="bg-white text-gray-900 hover:bg-white/90 rounded-full px-6 py-6 text-base"
                onClick={() => navigate("/room-selection")}
              >
                Start Your Design
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button 
                variant="outline"
                className="border-white/30 text-white hover:bg-white/10 hover:border-white/50 rounded-full px-6 py-6 text-base"
                onClick={() => navigate("/portfolio")}
              >
                View Portfolio
              </Button>
            </div>
          </div>
        </div>
        
        <div className="absolute bottom-10 left-0 right-0 flex justify-center">
          <div className="animate-bounce">
            <svg 
              className="w-6 h-6 text-white/70"
              fill="none" 
              stroke="currentColor" 
              viewBox="0 0 24 24" 
              xmlns="http://www.w3.org/2000/svg"
            >
              <path 
                strokeLinecap="round" 
                strokeLinejoin="round" 
                strokeWidth={2} 
                d="M19 14l-7 7m0 0l-7-7m7 7V3" 
              />
            </svg>
          </div>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="py-20 bg-design-neutral">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="font-serif text-3xl md:text-4xl font-medium mb-4">
              How It Works
            </h2>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
              Our platform combines artificial intelligence with interior design expertise to create your perfect space
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div 
                key={index} 
                className="bg-white p-6 rounded-lg border border-border/50 hover:shadow-md transition-shadow"
              >
                <div className="w-12 h-12 rounded-full bg-accent flex items-center justify-center mb-4">
                  {feature.icon}
                </div>
                <h3 className="font-serif text-xl font-medium mb-2">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.description}</p>
              </div>
            ))}
          </div>
          
          <div className="mt-16 text-center">
            <Button 
              className="rounded-full px-6 py-6 text-base"
              onClick={() => navigate("/room-selection")}
            >
              Try It Now
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </div>
        </div>
      </section>
      
      {/* Process Section */}
      <section className="py-20">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <span className="text-sm font-medium text-muted-foreground">OUR PROCESS</span>
              <h2 className="font-serif text-3xl md:text-4xl font-medium mt-2 mb-6">
                Design, Customize, Purchase
              </h2>
              <div className="space-y-6">
                <div className="flex items-start">
                  <div className="mr-4 flex-shrink-0 mt-1">
                    <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center">
                      1
                    </div>
                  </div>
                  <div>
                    <h3 className="font-serif text-xl font-medium mb-2">Select your room</h3>
                    <p className="text-muted-foreground">
                      Choose the space you want to design and provide basic dimensions and preferences.
                    </p>
                  </div>
                </div>
                
                <div className="flex items-start">
                  <div className="mr-4 flex-shrink-0 mt-1">
                    <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center">
                      2
                    </div>
                  </div>
                  <div>
                    <h3 className="font-serif text-xl font-medium mb-2">Review design options</h3>
                    <p className="text-muted-foreground">
                      Browse through multiple AI-generated design concepts tailored to your space and style.
                    </p>
                  </div>
                </div>
                
                <div className="flex items-start">
                  <div className="mr-4 flex-shrink-0 mt-1">
                    <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center">
                      3
                    </div>
                  </div>
                  <div>
                    <h3 className="font-serif text-xl font-medium mb-2">Customize and finalize</h3>
                    <p className="text-muted-foreground">
                      Refine your selected design with specific furniture pieces and accessories until perfect.
                    </p>
                  </div>
                </div>
                
                <div className="flex items-start">
                  <div className="mr-4 flex-shrink-0 mt-1">
                    <div className="w-8 h-8 rounded-full bg-primary text-primary-foreground flex items-center justify-center">
                      4
                    </div>
                  </div>
                  <div>
                    <h3 className="font-serif text-xl font-medium mb-2">Receive your BOQ and order</h3>
                    <p className="text-muted-foreground">
                      Get a detailed bill of quantities and place your order directly with our furniture suppliers.
                    </p>
                  </div>
                </div>
              </div>
              
              <div className="mt-8">
                <Button 
                  className="rounded-full px-6 py-6 text-base"
                  onClick={() => navigate("/room-selection")}
                >
                  Start Your Design
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Button>
              </div>
            </div>
            
            <div className="relative">
              <img 
                src="https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2000&q=80" 
                alt="Interior design process" 
                className="w-full h-auto rounded-lg shadow-xl"
              />
              <div className="absolute -bottom-6 -left-6 bg-white p-4 rounded-lg shadow-lg max-w-xs">
                <div className="flex items-center space-x-3 mb-2">
                  <Clock className="h-5 w-5 text-primary" />
                  <span className="font-medium">Fast Turnaround</span>
                </div>
                <p className="text-sm text-muted-foreground">
                  Get your designs in 24 hours and furniture delivered within 2 weeks
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      
      {/* Testimonials */}
      <section className="py-20 bg-design-neutral">
        <div className="container mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="font-serif text-3xl md:text-4xl font-medium mb-4">
              What Our Clients Say
            </h2>
            <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
              Hear from homeowners who have transformed their spaces using Interior Synergy
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {testimonials.map((testimonial, index) => (
              <div 
                key={index} 
                className="bg-white p-8 rounded-lg border border-border/50 hover:shadow-md transition-shadow"
              >
                <svg 
                  className="h-10 w-10 text-primary/20 mb-4" 
                  fill="currentColor" 
                  viewBox="0 0 32 32"
                >
                  <path d="M9.352 4C4.456 7.456 1 13.12 1 19.36c0 5.088 3.072 8.064 6.624 8.064 3.36 0 5.856-2.688 5.856-5.856 0-3.168-2.208-5.472-5.088-5.472-.576 0-1.344.096-1.536.192.48-3.264 3.552-7.104 6.624-9.024L9.352 4zm16.512 0c-4.8 3.456-8.256 9.12-8.256 15.36 0 5.088 3.072 8.064 6.624 8.064 3.264 0 5.856-2.688 5.856-5.856 0-3.168-2.304-5.472-5.184-5.472-.576 0-1.248.096-1.44.192.48-3.264 3.456-7.104 6.528-9.024L25.864 4z" />
                </svg>
                <p className="text-foreground mb-6">
                  "{testimonial.quote}"
                </p>
                <div>
                  <p className="font-medium">{testimonial.author}</p>
                  <p className="text-sm text-muted-foreground">{testimonial.role}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="py-20">
        <div className="container mx-auto px-6">
          <div className="bg-primary text-primary-foreground rounded-2xl p-10 md:p-16 text-center">
            <h2 className="font-serif text-3xl md:text-4xl font-medium mb-6 max-w-2xl mx-auto">
              Ready to Transform Your Space?
            </h2>
            <p className="text-lg max-w-2xl mx-auto mb-8 text-primary-foreground/80">
              Start your design journey today and create a home that reflects your personality and style.
            </p>
            <div className="flex flex-col sm:flex-row justify-center gap-4">
              <Button 
                className="bg-white text-primary hover:bg-white/90 rounded-full px-6 py-6 text-base"
                onClick={() => navigate("/room-selection")}
              >
                Start Your Design
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              <Button 
                variant="outline"
                className="border-white/30 text-white hover:bg-white/10 hover:border-white/50 rounded-full px-6 py-6 text-base"
                onClick={() => navigate("/contact")}
              >
                Contact Us
              </Button>
            </div>
          </div>
        </div>
      </section>
      
      {/* Footer */}
      <footer className="border-t py-16 bg-design-white">
        <div className="container mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <h3 className="font-serif text-xl font-medium mb-4">Interior Synergy</h3>
              <p className="text-muted-foreground mb-6">
                AI-powered interior design for the modern home.
              </p>
              <div className="flex space-x-4">
                <a href="#" className="text-muted-foreground hover:text-foreground">
                  <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M22.675 0h-21.35c-.732 0-1.325.593-1.325 1.325v21.351c0 .731.593 1.324 1.325 1.324h11.495v-9.294h-3.128v-3.622h3.128v-2.671c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.795.143v3.24l-1.918.001c-1.504 0-1.795.715-1.795 1.763v2.313h3.587l-.467 3.622h-3.12v9.293h6.116c.73 0 1.323-.593 1.323-1.325v-21.35c0-.732-.593-1.325-1.325-1.325z" />
                  </svg>
                </a>
                <a href="#" className="text-muted-foreground hover:text-foreground">
                  <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723 10.1 10.1 0 01-3.127 1.184 4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z" />
                  </svg>
                </a>
                <a href="#" className="text-muted-foreground hover:text-foreground">
                  <svg className="h-5 w-5" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M12 0C8.74 0 8.333.015 7.053.072 5.775.132 4.905.333 4.14.63c-.789.306-1.459.717-2.126 1.384S.935 3.35.63 4.14C.333 4.905.131 5.775.072 7.053.012 8.333 0 8.74 0 12s.015 3.667.072 4.947c.06 1.277.261 2.148.558 2.913.306.788.717 1.459 1.384 2.126.667.666 1.336 1.079 2.126 1.384.766.296 1.636.499 2.913.558C8.333 23.988 8.74 24 12 24s3.667-.015 4.947-.072c1.277-.06 2.148-.262 2.913-.558.788-.306 1.459-.718 2.126-1.384.666-.667 1.079-1.335 1.384-2.126.296-.765.499-1.636.558-2.913.06-1.28.072-1.687.072-4.947s-.015-3.667-.072-4.947c-.06-1.277-.262-2.149-.558-2.913-.306-.789-.718-1.459-1.384-2.126C21.319 1.347 20.651.935 19.86.63c-.765-.297-1.636-.499-2.913-.558C15.667.012 15.26 0 12 0zm0 2.16c3.203 0 3.585.016 4.85.071 1.17.055 1.805.249 2.227.415.562.217.96.477 1.382.896.419.42.679.819.896 1.381.164.422.36 1.057.413 2.227.057 1.266.07 1.646.07 4.85s-.015 3.585-.074 4.85c-.061 1.17-.256 1.805-.421 2.227-.224.562-.479.96-.899 1.382-.419.419-.824.679-1.38.896-.42.164-1.065.36-2.235.413-1.274.057-1.649.07-4.859.07-3.211 0-3.586-.015-4.859-.074-1.171-.061-1.816-.256-2.236-.421-.569-.224-.96-.479-1.379-.899-.421-.419-.69-.824-.9-1.38-.165-.42-.359-1.065-.42-2.235-.045-1.26-.061-1.649-.061-4.844 0-3.196.016-3.586.061-4.861.061-1.17.255-1.814.42-2.234.21-.57.479-.96.9-1.381.419-.419.81-.689 1.379-.898.42-.166 1.051-.361 2.221-.421 1.275-.045 1.65-.06 4.859-.06l.045.03zm0 3.678c-3.405 0-6.162 2.76-6.162 6.162 0 3.405 2.76 6.162 6.162 6.162 3.405 0 6.162-2.76 6.162-6.162 0-3.405-2.76-6.162-6.162-6.162zM12 16c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4-1.79 4-4 4zm7.846-10.405c0 .795-.646 1.44-1.44 1.44-.795 0-1.44-.646-1.44-1.44 0-.794.646-1.439 1.44-1.439.793-.001 1.44.645 1.44 1.439z" />
                  </svg>
                </a>
              </div>
            </div>
            
            <div>
              <h3 className="font-medium mb-4">Company</h3>
              <ul className="space-y-2">
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">About Us</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Careers</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Blog</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Press</a>
                </li>
              </ul>
            </div>
            
            <div>
              <h3 className="font-medium mb-4">Services</h3>
              <ul className="space-y-2">
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Interior Design</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Furniture Supply</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Commercial Projects</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Consultation</a>
                </li>
              </ul>
            </div>
            
            <div>
              <h3 className="font-medium mb-4">Support</h3>
              <ul className="space-y-2">
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">FAQ</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Contact</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Privacy Policy</a>
                </li>
                <li>
                  <a href="#" className="text-muted-foreground hover:text-foreground">Terms of Service</a>
                </li>
              </ul>
            </div>
          </div>
          
          <div className="border-t pt-8 mt-12 flex flex-col md:flex-row justify-between items-center">
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} Interior Synergy. All rights reserved.
            </p>
            <div className="mt-4 md:mt-0 flex items-center">
              <span className="text-sm text-muted-foreground mr-2">Made with</span>
              <CheckCircle className="h-4 w-4 text-primary" />
              <span className="text-sm text-muted-foreground ml-2">in modern design principles</span>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Index;
